### ISSUE TITLE
[feature request] Double-click on desktop unhides icons

### ISSUE THREAD

**Issue by noyannus** [HsiangHo/Kaka#27]
Please add the possibility to un-hide desktop icons by double-clicking the desktop.

**Comment by HsiangHo** [comment]
Hi, this feature has been implemented. Go to the preferences panel and check it. @noyannus

**Comment by noyannus** [comment]
Thank you for your reply. Now it works. I don't understand why it did not when I tried the first time - maybe a reboot was necessary? I'm puzzled.
